### ISSUE TITLE
Uncaught Exception: InvalidTokenError at Object.<anonymous> 

### ISSUE THREAD

**Issue by codingChewie** [auth0-blog/electron-openid-oauth#3]
Ran across the [blog tutorial ](https://auth0.com/blog/securing-electron-applications-with-openid-connect-and-oauth-2/) and since I wanted a way to add sign in to my electron app I gave this a shot and created an account. 

While following the blog post there appears to be some content that was removed. When following the post there was no mention of the directory `services` prior to the line of:

>  So, create a new file called auth-service.js under the services directory and insert the following code into it:

When I code from the post I would never see a login page it would go directly to the dashboard and when logout was clicked it would close the application. 

Initially I received a Node.js version error, which was noted with:

> Note: If you run into an error saying that "keytar was compiled against a different Node.js version using", you will have to install electron-rebuild and run it locally ./node_modules/.bin/electron-rebuild, as explained here.

that didn't work for me. After checking StackOverflow I did run across "[Node - was compiled against a different Node.js version using NODE_MODULE_VERSION 51](https://stackoverflow.com/questions/46384591/node-was-compiled-against-a-different-node-js-version-using-node-module-versio)" that was resolved from the [answer](https://stackoverflow.com/a/52796884/1952287): 

* Run `npm i -D electron-rebuild` to add the electron-rebuild package
* Remove the node-modules folder, as well as the packages-lock.json file.
* Run `npm i` to install all modules.
* Run `./node_modules/.bin/electron-rebuild` to rebuild everything

that seemed to solve the node issue and here is the updated package.json:

```
{
  "name": "front",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron ./"
  },
  "author": "",
  "devDependencies": {
    "electron": "^2.0.2",
    "electron-rebuild": "^1.8.4"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "jwt-decode": "^2.2.0",
    "keytar": "^4.4.0",
    "request": "^2.88.0"
  }
}
```

after not getting that to work because I would get an error of:

> Not allowed to load local resource: file:///callback?code=nD7usqE-2c6Oo7mx

I cloned this repo. Added my variables to the fronend and backend files but I get the error of:

> Uncaught Exception: InvalidTokenError at Object.<anonymous> 

and that is after the [pushed changes](https://github.com/auth0-blog/electron-openid-oauth/commit/39ded231acba7319c2665f4dec16e8418e2245f8) noted in this [comment](https://auth0.com/blog/securing-electron-applications-with-openid-connect-and-oauth-2/#comment-4197261084) were made. Please advise.

**Comment by codingChewie** [comment]
Terminal response:

```
failure
https://SETTINGS-DOMAIN.auth0.com/authorize?audience=API-IDENTIFIER&scope=openid profile offline_access&response_type=code&client_id=CLIENT-ID-FROM-UNDER-APP-NAME&redirect_uri=file:///callback
2019-04-15 12:22:56.634 Electron[78284:4024537] *** WARNING: Textured window <EventDispatchingWindow: 0x7fc835fc6040> is getting an implicitly transparent titlebar. This will break when linking against newer SDKs. Use NSWindow's -titlebarAppearsTransparent=YES instead.
```

After adding `win.webContents.openDevTools()` I get in the console:

`Not allowed to load local resource: file:///callback?code=kJ1tRTE8tJ4dC1rk`

**Comment by codingChewie** [comment]
full error message:

```
Uncaught Exception:
InvalidTokenError
    at Object.<anonymous> (/Users/codingChewie/electron-openid-oauth-master/frontend/node_modules/jwt-decode/lib/index.js:9:31)
    at Object.<anonymous> (/Users/codingChewie/electron-openid-oauth-master/frontend/node_modules/jwt-decode/lib/index.js:28:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/codingChewie/electron-openid-oauth-master/frontend/services/auth-service.js:1:174)
```

**Comment by jbroquist** [comment]
@codingChewie How did you solve this? I'm running into the same issue.
